config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  resources :aulas
  devise_for :usuarios, controllers: { registrations: "registrations" } # redireciona após cadastro
  get '/usuario' => "pages#index", :as => :usuario_root # redireciona após login
  get "/pages", to: "pages#index"
  root 'homes#index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :cadastros
  resources :homes
  get 'homepage/new'
  get 'homepage/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cadastro.rb
class Cadastro < ApplicationRecord
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :set_cadastro, only: %i[ show edit update destroy ]

  # GET /cadastros or /cadastros.json
  def index
    @cadastros = Cadastro.all
  end

  # GET /cadastros/1 or /cadastros/1.json
  def show
  end

  # GET /cadastros/new
  def new
    @cadastro = Cadastro.new
  end

  # GET /cadastros/1/edit
  def edit
  end

  # POST /cadastros or /cadastros.json
  def create
    @cadastro = Cadastro.new(cadastro_params)

    respond_to do |format|
      if @cadastro.save
        format.html { redirect_to @cadastro, notice: "Cadastro was successfully created." }
        format.json { render :show, status: :created, location: @cadastro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastros/1 or /cadastros/1.json
  def update
    respond_to do |format|
      if @cadastro.update(cadastro_params)
        format.html { redirect_to @cadastro, notice: "Cadastro was successfully updated." }
        format.json { render :show, status: :ok, location: @cadastro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1 or /cadastros/1.json
  def destroy
    @cadastro.destroy
    respond_to do |format|
      format.html { redirect_to cadastros_url, notice: "Cadastro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro
      @cadastro = Cadastro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cadastro_params
      params.require(:cadastro).permit(:name, :birthday_date, :email, :password, :confirm_password)
    end
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/views/cadastros/_form.html.erb
<%= simple_form_for(@cadastro) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class = "form-inputs">

  <%=f.input :name, label: "Nome Completo", error: "Nome completo é obrigatório", placeholder: "João da Silva" %>
  <%=f.input :birthday_date, label: "Data de aniversário"%>
  <%=f.input :email, placeholder: "user@domain.com", label: "Email"%>
  <%=f.input :password, label: "Senha"%>
  <%=f.input :confirm_password, label: "Confirmar Senha"%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cadastros/edit.html.erb
<h1>Editando Cadastro</h1>

<%= render 'form', cadastro: @cadastro %>

<%= link_to 'Show', @cadastro %> |
<%= link_to 'Back', cadastros_path %>

app/views/cadastros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cadastros</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthday date</th>
      <th>Email</th>
      <th>Password</th>
      <th>Confirm password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadastros.each do |cadastro| %>
      <tr>
        <td><%= cadastro.name %></td>
        <td><%= cadastro.birthday_date %></td>
        <td><%= cadastro.email %></td>
        <td><%= cadastro.password %></td>
        <td><%= cadastro.confirm_password %></td>
        <td><%= link_to 'Show', cadastro %></td>
        <td><%= link_to 'Edit', edit_cadastro_path(cadastro) %></td>
        <td><%= link_to 'Destroy', cadastro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cadastro', new_cadastro_path %>

app/views/cadastros/new.html.erb
<h1>Novo Cadastro</h1>

<%= render 'form', cadastro: @cadastro %>

<%= link_to 'Back', cadastros_path %>

app/views/cadastros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cadastro.name %>
</p>

<p>
  <strong>Birthday date:</strong>
  <%= @cadastro.birthday_date %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cadastro.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @cadastro.password %>
</p>

<p>
  <strong>Confirm password:</strong>
  <%= @cadastro.confirm_password %>
</p>

<%= link_to 'Edit', edit_cadastro_path(@cadastro) %> |
<%= link_to 'Back', cadastros_path %>