config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  resources :aulas
  devise_for :usuarios, controllers: { registrations: "registrations" } # redireciona após cadastro
  get '/usuario' => "pages#index", :as => :usuario_root # redireciona após login
  get "/pages", to: "pages#index"
  root 'homes#index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :cadastros
  resources :homes
  get 'homepage/new'
  get 'homepage/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :cursos
end

app/controllers/aulas_controller.rb
class AulasController < ApplicationController
  before_action :set_aula, only: %i[ show edit update destroy ]

  # GET /aulas or /aulas.json
  def index
    @aulas = Aula.all
  end

  # GET /aulas/1 or /aulas/1.json
  def show
  end

  # GET /aulas/new
  def new
    @aula = Aula.new
  end

  # GET /aulas/1/edit
  def edit
  end

  # POST /aulas or /aulas.json
  def create
    @aula = Aula.new(aula_params)

    respond_to do |format|
      if @aula.save
        format.html { redirect_to @aula, notice: "Aula was successfully created." }
        format.json { render :show, status: :created, location: @aula }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aulas/1 or /aulas/1.json
  def update
    respond_to do |format|
      if @aula.update(aula_params)
        format.html { redirect_to @aula, notice: "Aula was successfully updated." }
        format.json { render :show, status: :ok, location: @aula }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aulas/1 or /aulas/1.json
  def destroy
    @aula.destroy
    respond_to do |format|
      format.html { redirect_to aulas_url, notice: "Aula was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aula
      @aula = Aula.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aula_params
      params.require(:aula).permit(:titulo, :url)
    end
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/views/aulas/_form.html.erb
<%= simple_form_for(@aula) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/aulas/edit.html.erb
<h1>Editing Aula</h1>

<%= render 'form', aula: @aula %>

<%= link_to 'Show', @aula %> |
<%= link_to 'Back', aulas_path %>

app/views/aulas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aulas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aulas.each do |aula| %>
      <tr>
        <td><%= aula.titulo %></td>
        <td><%= aula.url %></td>
        <td><%= link_to 'Show', aula %></td>
        <td><%= link_to 'Edit', edit_aula_path(aula) %></td>
        <td><%= link_to 'Destroy', aula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aula', new_aula_path %>

app/views/aulas/new.html.erb
<h1>New Aula</h1>

<%= render 'form', aula: @aula %>

<%= link_to 'Back', aulas_path %>

app/views/aulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @aula.titulo %>
</p>

<p>
  <strong>Url:</strong>
  <%= @aula.url %>
</p>

<%= link_to 'Edit', edit_aula_path(@aula) %> |
<%= link_to 'Back', aulas_path %>