config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  resources :aulas
  devise_for :usuarios, controllers: { registrations: "registrations" } # redireciona após cadastro
  get '/usuario' => "pages#index", :as => :usuario_root # redireciona após login
  get "/pages", to: "pages#index"
  root 'homes#index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :cadastros
  resources :homes
  get 'homepage/new'
  get 'homepage/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/curso.rb
class Curso < ApplicationRecord
  has_many :aulas
  accepts_nested_attributes_for :aulas, reject_if: ->(attributes){ attributes['url'].blank? }, allow_destroy: true
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: %i[ show edit update destroy ]

  # GET /cursos or /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1 or /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos or /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: "Curso was successfully created." }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1 or /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: "Curso was successfully updated." }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1 or /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: "Curso was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def curso_params
      params.require(:curso).permit(:titulo, :link, :aulas => [:titulo, :url])
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<%= simple_form_for(@curso) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :link %>
    <%= f.association :aulas %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Show', @curso %> |
<%= link_to 'Back', cursos_path %>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Link</th>
      <th>
        Aulas
        <p>Titulo | URL</p>
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.titulo %></td>
        <td><%= curso.link %></td>
        <td>
          <% curso.aulas.each do |aula| %>
            <span><%= aula.titulo %> | </span>
            <span><%= aula.url %></span>
          <% end %>
        </td>

        <br>
        <br>
        <td><%= link_to 'Show', curso %></td>
        <td><%= link_to 'Edit', edit_curso_path(curso) %></td>
        <td><%= link_to 'Destroy', curso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curso', new_curso_path %>

app/views/cursos/new.html.erb
<div class="main-container">
  <h1>Novo curso</h1>

  <%= render 'form', curso: @curso %>

  <%= link_to 'Back', cursos_path %>

</div>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @curso.titulo %>
</p>

<p>
  <strong>Link:</strong>
  <%= @curso.link %>
</p>

<p>
  <strong>Aulas:</strong>
  <%= @curso.aulas_id %>
</p>

<%= link_to 'Edit', edit_curso_path(@curso) %> |
<%= link_to 'Back', cursos_path %>