config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  resources :aulas
  devise_for :usuarios, controllers: { registrations: "registrations" } # redireciona após cadastro
  get '/usuario' => "pages#index", :as => :usuario_root # redireciona após login
  get "/pages", to: "pages#index"
  root 'homes#index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :cadastros
  resources :homes
  get 'homepage/new'
  get 'homepage/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :cursos
end

app/models/cadastro.rb
class Cadastro < ApplicationRecord
end

app/models/curso.rb
class Curso < ApplicationRecord
  has_many :aulas
  accepts_nested_attributes_for :aulas, reject_if: ->(attributes){ attributes['url'].blank? }, allow_destroy: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/aulas_controller.rb
class AulasController < ApplicationController
  before_action :set_aula, only: %i[ show edit update destroy ]

  # GET /aulas or /aulas.json
  def index
    @aulas = Aula.all
  end

  # GET /aulas/1 or /aulas/1.json
  def show
  end

  # GET /aulas/new
  def new
    @aula = Aula.new
  end

  # GET /aulas/1/edit
  def edit
  end

  # POST /aulas or /aulas.json
  def create
    @aula = Aula.new(aula_params)

    respond_to do |format|
      if @aula.save
        format.html { redirect_to @aula, notice: "Aula was successfully created." }
        format.json { render :show, status: :created, location: @aula }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aulas/1 or /aulas/1.json
  def update
    respond_to do |format|
      if @aula.update(aula_params)
        format.html { redirect_to @aula, notice: "Aula was successfully updated." }
        format.json { render :show, status: :ok, location: @aula }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aulas/1 or /aulas/1.json
  def destroy
    @aula.destroy
    respond_to do |format|
      format.html { redirect_to aulas_url, notice: "Aula was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aula
      @aula = Aula.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aula_params
      params.require(:aula).permit(:titulo, :url)
    end
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: %i[ show edit update destroy ]

  # GET /cursos or /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1 or /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos or /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: "Curso was successfully created." }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1 or /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: "Curso was successfully updated." }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1 or /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: "Curso was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def curso_params
      params.require(:curso).permit(:titulo, :link, :aulas => [:titulo, :url])
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_usuario!, only: %i[ index ]


  # GET /homes or /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1 or /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuscadorInteligente</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      abbr {
        text-decoration: none !important
      }
    </style>
  </head>

  <body>
    <!-- Navbar -->
    <div class="w3-top">
      <div class="buscador-inteligente w3-red w3-card w3-left-align w3-large">
        <a class="buscador-inteligente-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
        <a href="#" class="buscador-inteligente-item w3-button w3-padding-large w3-white">BuscadorInteligente</a>

        <% if usuario_signed_in? %>
            <%= button_to "Sair", destroy_usuario_session_path, method: :delete,
            :class => "buscador-inteligente-item w3-button w3-padding-large w3-white w3-right", 
            form: {style: 'display: inline'} %>
        <% else %>
          <%= link_to "Criar conta", new_usuario_registration_path, :class => "buscador-inteligente-item w3-button w3-padding-large w3-white w3-right w3-border-left" %>
          <%= link_to "Entrar", new_usuario_session_path, :class => "buscador-inteligente-item w3-button w3-padding-large w3-white w3-right" %>
        <% end %>

      </div>

      <!-- Navbar on small screens -->
      <div id="navDemo" class="buscador-inteligente-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
      </div>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
     <!-- **DO THIS**: -->
    <!--   Replace SDK_VERSION_NUMBER with the current SDK version number -->
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.1019.0.min.js"></script>
    <script>
    var albumBucketName = "buscador-inteligente-eng";
var bucketRegion = "sa-east-1";
var IdentityPoolId = "sa-east-1:b6d2fb14-b0a7-485e-8744-e75931912b5e";

AWS.config.update({
  region: bucketRegion,
  credentials: new AWS.CognitoIdentityCredentials({
    IdentityPoolId: IdentityPoolId
  })
});

var s3 = new AWS.S3({
  apiVersion: "2006-03-01",
  params: { Bucket: albumBucketName }
});

function getHtml(template) {
    return template.join('\n');
}
// snippet-end:[s3.JavaScript.photoAlbumExample.config]

// snippet-start:[s3.JavaScript.photoAlbumExample.listSalas]
function listSalas() {
  s3.listObjects({ Delimiter: "/" }, function(err, data) {
    if (err) {
      return alert("Erro ao listar suas salas: " + err.message);
    } else {
        var albums = data.CommonPrefixes.map(function(commonPrefix) {
        var prefix = commonPrefix.Prefix;
        var albumName = decodeURIComponent(prefix.replace("/", ""));
        return getHtml([
          "<li>",
          "<span onclick=\"deleteAlbum('" + albumName + "')\">X</span>",
          "<span onclick=\"viewAlbum('" + albumName + "')\">",
          albumName,
          "</span>",
          "</li>"
        ]);
      });
      var message = albums.length
        ? getHtml([
            "<p>Clique no nome da sala para ver seus vídeos.</p>",
            "<p>Clique no X para deletar a Sala.</p>"
          ])
        : "<p>Você não possui nenhuma sala, crie uma! :).";
      var htmlTemplate = [
        "<h2>Minhas Salas: </h2>",
        message,
        "<ul>",
        getHtml(albums),
        "</ul>",
        "<button onclick=\"createAlbum(prompt('Nome da Sala:'))\">",
        "Criar Sala",
        "</button>"
      ];
      document.getElementById("app").innerHTML = getHtml(htmlTemplate);
    }
  });
}
// snippet-end:[s3.JavaScript.photoAlbumExample.listSalas]

// snippet-start:[s3.JavaScript.photoAlbumExample.createAlbum]
function createAlbum(albumName) {
  albumName = albumName.trim();
  if (!albumName) {
    return alert("O nome da sala deve ter pelo menos um caracter que não é um espaço.");
  }
  if (albumName.indexOf("/") !== -1) {
    return alert("O nome da sala não pode conter barras.");
  }
  var albumKey = encodeURIComponent(albumName);
  s3.headObject({ Key: albumKey }, function(err, data) {
    if (!err) {
      return alert("Sala ja existe.");
    }
    if (err.code !== "NotFound") {
      return alert("Erro ao criar sala " + err.message);
    }
    s3.putObject({ Key: albumKey }, function(err, data) {
      if (err) {
        return alert("Erro ao criar sala " + err.message);
      }
      alert("Sala criada com sucesso.");
      viewAlbum(albumName);
    });
  });
}
// snippet-end:[s3.JavaScript.photoAlbumExample.createAlbum]

// snippet-start:[s3.JavaScript.photoAlbumExample.viewAlbum]
function viewAlbum(albumName) {
  var albumPhotosKey = encodeURIComponent(albumName) + "/";
  s3.listObjects({ Prefix: albumPhotosKey }, function(err, data) {
    if (err) {
      return alert("Erro ao visualizar aulas: " + err.message);
    }
    // 'this' references the AWS.Response instance that represents the response
    var href = this.request.httpRequest.endpoint.href;
    var bucketUrl = href + albumBucketName + "/";

    var photos = data.Contents.map(function(photo) {
      var photoKey = photo.Key;
      var photoUrl = bucketUrl + encodeURIComponent(photoKey);
      var n =photoKey.indexOf('/');
      var subtitles = 'https://buscador-inteligente-eng-legendas.s3.sa-east-1.amazonaws.com/'+ photoKey.slice(n+1)+'.vtt';
      console.log(subtitles)
      return getHtml([
        "<span>",
        "<div>",
        '<video width="320" height="240" controls crossorigin="anonymous"><source src="'+photoUrl+'" type="video/mp4"><track src="' + subtitles + '" kind="subtitles" srclang="pt" label="Portugues">',
        "</div>",
        "<div>",
        "<span onclick=\"deletePhoto('" +
          albumName +
          "','" +
          photoKey +
          "')\">",
        "X",
        "</span>",
        "<span>",
        photoKey.replace(albumPhotosKey, ""),
        "</span>",
        "</div>",
        "</span>"
      ]);
    });
    var message = photos.length
      ? "<p>Clique no X para deletar o vídeo da sua Sala</p>"
      : "<p>Você não possui nenhum vídeo, por favor adicione um vídeo</p>";
    var htmlTemplate = [
      "<h2>",
      "Sala: " + albumName,
      "</h2>",
      message,
      "<div>",
      getHtml(photos),
      "</div>",
      '<input id="photoupload" type="file" accept="video/*">',
      '<button id="addphoto" onclick="addPhoto(\'' + albumName + "')\">",
      "Adicionar Aula",
      "</button>",
      '<button onclick="listSalas()">',
      "Voltar para minhas salas",
      "</button>"
    ];
    document.getElementById("app").innerHTML = getHtml(htmlTemplate);
  });
}
// snippet-end:[s3.JavaScript.photoAlbumExample.viewAlbum]

// snippet-start:[s3.JavaScript.photoAlbumExample.addPhoto]
function addPhoto(albumName) {
  var files = document.getElementById("photoupload").files;
  if (!files.length) {
    return alert("Escolha um vídeo antes.");
  }
  var file = files[0];
  var fileName = file.name;
  var albumPhotosKey = encodeURIComponent(albumName) + "/";

  var photoKey = albumPhotosKey + fileName;

  // Use S3 ManagedUpload class as it supports multipart uploads
  var upload = new AWS.S3.ManagedUpload({
    params: {
      Bucket: albumBucketName,
      Key: photoKey,
      Body: file,
      ACL:'public-read'
    }
  });

  var promise = upload.promise();

  promise.then(
    function(data) {
      alert("Vídeo enviado com sucesso.");
      viewAlbum(albumName);
    },
    function(err) {
      return alert("Erro ao enviar seu vídeo: ", err.message);
    }
  );
}
// snippet-end:[s3.JavaScript.photoAlbumExample.addPhoto]

// snippet-start:[s3.JavaScript.photoAlbumExample.deletePhoto]
function deletePhoto(albumName, photoKey) {
  s3.deleteObject({ Key: photoKey }, function(err, data) {
    if (err) {
      return alert("Erro ao deletar vídeo: ", err.message);
    }
    alert("Vídeo deletado com sucesso.");
    viewAlbum(albumName);
  });
}
// snippet-end:[s3.JavaScript.photoAlbumExample.deletePhoto]

// snippet-start:[s3.JavaScript.photoAlbumExample.deleteAlbum]
function deleteAlbum(albumName) {
  var albumKey = encodeURIComponent(albumName) + "/";
  s3.listObjects({ Prefix: albumKey }, function(err, data) {
    if (err) {
      return alert("Erro ao deletar Sala: ", err.message);
    }
    var objects = data.Contents.map(function(object) {
      return { Key: object.Key };
    });
    s3.deleteObjects(
      {
        Delete: { Objects: objects, Quiet: true }
      },
      function(err, data) {
        if (err) {
          return alert("Erro ao deletar Sala", err.message);
        }
        alert("Sala deletada com sucesso.");
        listSalas();
      }
    );
  });
}
    </script>
    <script>
       listSalas();
    </script>
  </head>
  <body>
    <h1>Buscador inteligente</h1>
    <div id="app"></div>
  </body>
</html>